services:
  license-audit:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.license-audit
  java-common:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.java-common
    volumes:
      - .:/app
  java8-mazerunner:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.java8-mazerunner
    volumes:
      - .:/app
  java17-mazerunner:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.java17-mazerunner
  java-publisher:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.java-publisher
    environment:
      KEY:
      KEY_ID:
      KEY_PASS:
      PUBLISH_USER:
      PUBLISH_PASS: