version: '3.6'
services:
  license-audit:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.license-audit
  java-common:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.java-common
  java8-mazerunner:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.java8-mazerunner
  java17-mazerunner:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.java17-mazerunner