steps:
  - label: 'Audit current licenses'
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v3.7.0:
          run: license-audit

  - label: ':docker: Assemble project'
    key: 'java-jvm-build'
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v3.7.0:
          run: java-common
    command: './gradlew :bugsnag:assemble :bugsnag-spring:javax:assemble :bugsnag-spring:assemble'

  - label: ':docker: Run JVM tests'
    key: 'java-jvm-tests'
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v3.7.0:
          run: java-common
    command: './gradlew check test'

  - label: ':docker: Mazerunner java8 tests batch 1'
    key: 'java-mazerunner-tests-1'
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v3.7.0:
          run: java8-mazerunner
    command: 'bundle exec maze-runner --exclude=features/[^a-m].*.feature'

  - label: ':docker: Mazerunner java8 tests batch 2'
    key: 'java-mazerunner-tests-2'
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v3.7.0:
          pull: java8-mazerunner
          run: java8-mazerunner
    command: 'bundle exec maze-runner --exclude=features/[^n-z].*.feature'

  - label: ':docker: Mazerunner java17 tests batch 1'
    key: 'java-mazerunner-tests-3'
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v3.7.0:
          run: java17-mazerunner
    command: 'bundle exec maze-runner --exclude=features/[^a-m].*.feature'

  - label: ':docker: Mazerunner java17 tests batch 2'
    key: 'java-mazerunner-tests-4'
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v3.7.0:
          pull: java17-mazerunner
          run: java17-mazerunner
    command: 'bundle exec maze-runner --exclude=features/[^n-z].*.feature'
