FROM openjdk:17-jdk-slim
WORKDIR /app

RUN apt-get update > /dev/null
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y zip

# Force download of gradle zip early to avoid repeating
# if Docker cache is invalidated by branch changes.
COPY gradlew gradle.properties /app/
COPY gradle/ /app/gradle/
ENV GRADLE_OPTS="-Dorg.gradle.daemon=false"
COPY settings.gradle /app/
RUN ./gradlew
