FROM 855461928731.dkr.ecr.us-west-1.amazonaws.com/android:java-release as java-publisher

WORKDIR /app

# Copy gradle files
COPY gradlew gradle.properties /app/
COPY gradle/ /app/gradle/
COPY build.gradle settings.gradle.kts release.gradle.kts common.gradle.kts /app/

# Copy sdk source files
COPY bugsnag/ bugsnag/
COPY bugsnag-spring/ bugsnag-spring/
COPY scripts/ scripts/
COPY LICENSE LICENSE

CMD "scripts/docker-publish.sh"
